# This is set up for a Logitech Extreme 3D Pro joystick
# Button 0 is the trigger, all the other ones are labeled with 
# the button number + 1 (because muggles use 1-based addressing)
#
# If you put the turbo speeds to over 1, the conversion to motor speeds
# will have an issue as it passes over 1 that leads to sudden reversing of the motor.

teleop_twist_joy:
  axis_linear: 1
  scale_linear: 0.4
  scale_linear_turbo: 1.0
  axis_angular: 0
  scale_angular: 0.6
  scale_angular_turbo: 1.0
  enable_button: 1
  enable_turbo_button: 0
joy_node:
  deadzone: 0.1
  autorepeat_rate: 20
  dev: /dev/input/js0